# Generated by Django 4.1.3 on 2023-01-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_comment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_choice',
            field=models.CharField(choices=[('news', 'Статья'), ('article', 'Новость')], default='Статьи', max_length=255),
        ),
    ]
