# Generated by Django 4.1.3 on 2023-01-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_post_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_choice',
            field=models.CharField(choices=[('Новости', 'News'), ('Статьи', 'Articles')], default='Статьи', max_length=255),
        ),
    ]
